CREATE DATABASE PATIENTS;
USE PATIENTS;
CREATE TABLE account1(
id int NOT NULL  auto_increment,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);
select * from account1;

